spring.application.name=Assignment1
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
spring.threads.virtual.enabled=true
openai.api.base-url=https://api.openai.com